// Shared demo data for static pages (no DB required)

export const DEMO_JOBS = [
  {
    id: "1",
    title: "Réceptionniste bilingue",
    slug: "receptionniste-bilingue-marrakech",
    jobCategory: "RECEPTION" as const,
    contractType: "CDI" as const,
    city: "Marrakech",
    region: "MARRAKECH_SAFI",
    salary: "6 000 - 8 000 MAD",
    experience: "2-3 ans d'expérience en réception hôtelière",
    skills: ["Français", "Anglais", "Arabe", "Opera PMS", "Accueil client"],
    deadline: "2026-05-30",
    createdAt: "2026-03-30",
    description:
      "Nous recherchons un(e) réceptionniste bilingue pour rejoindre notre équipe au sein du prestigieux Royal Mansour Marrakech. Vous serez en charge de l'accueil des clients internationaux, de la gestion des réservations et du suivi des demandes spéciales. Vous devez maîtriser le français, l'anglais et l'arabe, et avoir une expérience confirmée dans l'hôtellerie de luxe. Connaissance du logiciel Opera PMS souhaitée.",
    company: {
      id: "c1",
      name: "Royal Mansour Marrakech",
      logo: null,
      verified: true,
      description:
        "Palace 5 étoiles situé au cœur de la médina de Marrakech, le Royal Mansour est l'un des hôtels les plus prestigieux du Maroc. Propriété de la Fondation Mohammed VI, il offre une expérience unique dans des riads privés.",
      city: "Marrakech",
      sector: "Hôtellerie de luxe",
      website: "https://www.royalmansour.com",
      activeJobs: 4,
    },
  },
  {
    id: "2",
    title: "Chef de cuisine - Restaurant gastronomique",
    slug: "chef-cuisine-agadir",
    jobCategory: "CUISINE" as const,
    contractType: "CDI" as const,
    city: "Agadir",
    region: "SOUSS_MASSA",
    salary: "12 000 - 18 000 MAD",
    experience: "5+ ans en cuisine gastronomique",
    skills: ["Cuisine marocaine", "Cuisine internationale", "Gestion d'équipe", "HACCP", "Créativité culinaire"],
    deadline: "2026-05-15",
    createdAt: "2026-03-28",
    description:
      "Le Sofitel Agadir Royal Bay recherche un Chef de cuisine expérimenté pour diriger le restaurant gastronomique de l'hôtel. Vous concevrez les menus, superviserez la brigade et garantirez l'excellence culinaire. Expérience en cuisine marocaine et internationale requise. Certification HACCP obligatoire.",
    company: {
      id: "c2",
      name: "Sofitel Agadir Royal Bay",
      logo: null,
      verified: true,
      description:
        "Hôtel 5 étoiles en bord de mer à Agadir, le Sofitel Royal Bay combine luxe contemporain et art de vivre marocain avec vue imprenable sur l'océan Atlantique.",
      city: "Agadir",
      sector: "Hôtellerie",
      website: "https://www.sofitel.com",
      activeJobs: 3,
    },
  },
  {
    id: "3",
    title: "Guide touristique certifié",
    slug: "guide-touristique-fes",
    jobCategory: "GUIDE" as const,
    contractType: "FREELANCE" as const,
    city: "Fès",
    region: "FES_MEKNES",
    salary: "8 000 - 12 000 MAD",
    experience: "3+ ans en tant que guide",
    skills: ["Histoire du Maroc", "Français", "Anglais", "Espagnol", "Premiers secours"],
    deadline: "2026-06-01",
    createdAt: "2026-03-26",
    description:
      "Nous recherchons un guide touristique certifié pour accompagner nos groupes dans la découverte de la médina de Fès, classée au patrimoine mondial de l'UNESCO. Vous devez être passionné par l'histoire et la culture marocaines et parler au moins 3 langues.",
    company: {
      id: "c3",
      name: "Fès Médina Tours",
      logo: null,
      verified: false,
      description:
        "Agence spécialisée dans les visites guidées de la médina de Fès et des sites historiques de la région.",
      city: "Fès",
      sector: "Agence de voyage",
      website: "https://www.fesmedinatours.com",
      activeJobs: 2,
    },
  },
  {
    id: "4",
    title: "Directeur d'hôtel 4 étoiles",
    slug: "directeur-hotel-casablanca",
    jobCategory: "MANAGEMENT" as const,
    contractType: "CDI" as const,
    city: "Casablanca",
    region: "CASABLANCA_SETTAT",
    salary: "25 000 - 35 000 MAD",
    experience: "8+ ans en management hôtelier",
    skills: ["Revenue management", "Leadership", "Gestion financière", "Anglais courant", "Stratégie commerciale"],
    deadline: "2026-05-01",
    createdAt: "2026-03-24",
    description:
      "Le Hyatt Regency Casablanca recrute un Directeur d'hôtel pour piloter l'ensemble des opérations de l'établissement. Vous serez responsable de la stratégie commerciale, de la satisfaction client et de la gestion des équipes (150+ collaborateurs). Poste à forte dimension stratégique.",
    company: {
      id: "c4",
      name: "Hyatt Regency Casablanca",
      logo: null,
      verified: true,
      description:
        "Situé dans le quartier d'affaires de Casablanca, le Hyatt Regency est un hôtel 5 étoiles réputé pour son service d'excellence et sa gastronomie.",
      city: "Casablanca",
      sector: "Hôtellerie",
      website: "https://www.hyatt.com",
      activeJobs: 5,
    },
  },
  {
    id: "5",
    title: "Animateur touristique polyvalent",
    slug: "animateur-touristique-essaouira",
    jobCategory: "ANIMATION" as const,
    contractType: "SAISONNIER" as const,
    city: "Essaouira",
    region: "MARRAKECH_SAFI",
    salary: "5 000 - 7 000 MAD",
    experience: "1-2 ans en animation",
    skills: ["Animation de groupe", "Sports nautiques", "Musique", "Premiers secours", "Énergie positive"],
    deadline: "2026-04-30",
    createdAt: "2026-03-22",
    description:
      "Rejoignez notre équipe d'animation pour la saison estivale à Essaouira ! Vous organiserez des activités sportives, culturelles et ludiques pour nos clients. Ambiance conviviale et internationale garantie. Logement et repas fournis.",
    company: {
      id: "c5",
      name: "Mogador Hotels & Resorts",
      logo: null,
      verified: true,
      description:
        "Chaîne hôtelière marocaine présente à Essaouira, Marrakech et Agadir, spécialisée dans le tourisme balnéaire et culturel.",
      city: "Essaouira",
      sector: "Hôtellerie",
      website: "https://www.mogadorhotels.com",
      activeJobs: 6,
    },
  },
  {
    id: "6",
    title: "Responsable spa et bien-être",
    slug: "responsable-spa-tanger",
    jobCategory: "BIEN_ETRE" as const,
    contractType: "CDI" as const,
    city: "Tanger",
    region: "TANGER_TETOUAN_AL_HOCEIMA",
    salary: "10 000 - 14 000 MAD",
    experience: "4+ ans en gestion de spa",
    skills: ["Gestion de spa", "Soins esthétiques", "Management", "Anglais", "Connaissance des produits bio"],
    deadline: "2026-05-20",
    createdAt: "2026-03-20",
    description:
      "Le Hilton Tanger City Center recherche un(e) responsable spa pour diriger notre espace bien-être de 1 500m². Vous gérerez une équipe de 12 thérapeutes, développerez la carte des soins et assurerez la rentabilité du centre. Expérience en spa hôtelier de luxe requise.",
    company: {
      id: "c6",
      name: "Hilton Tanger City Center",
      logo: null,
      verified: true,
      description:
        "Hôtel 5 étoiles au cœur de Tanger, le Hilton offre une vue panoramique sur le détroit de Gibraltar et dispose d'un spa de classe mondiale.",
      city: "Tanger",
      sector: "Hôtellerie",
      website: "https://www.hilton.com",
      activeJobs: 3,
    },
  },
  {
    id: "7",
    title: "Stagiaire en gestion hôtelière",
    slug: "stagiaire-gestion-hoteliere-rabat",
    jobCategory: "MANAGEMENT" as const,
    contractType: "STAGE" as const,
    city: "Rabat",
    region: "RABAT_SALE_KENITRA",
    salary: "2 500 MAD",
    experience: "Étudiant en hôtellerie/tourisme",
    skills: ["Pack Office", "Anglais", "Organisation", "Communication", "Esprit d'équipe"],
    deadline: "2026-06-15",
    createdAt: "2026-03-18",
    description:
      "Stage de 6 mois au sein de la direction de l'hôtel. Vous participerez à la gestion opérationnelle, au suivi de la qualité et au développement commercial. Formation assurée par des professionnels expérimentés. Idéal pour les étudiants en fin de cursus hôtellerie/tourisme.",
    company: {
      id: "c7",
      name: "The View Hotel Rabat",
      logo: null,
      verified: false,
      description:
        "Boutique hôtel moderne au cœur de Rabat, offrant une vue exceptionnelle sur la vallée du Bouregreg.",
      city: "Rabat",
      sector: "Hôtellerie",
      website: "https://www.theviewhotel.ma",
      activeJobs: 1,
    },
  },
  {
    id: "8",
    title: "Chef de rang - Restaurant panoramique",
    slug: "chef-rang-restaurant-ouarzazate",
    jobCategory: "SERVICE" as const,
    contractType: "CDD" as const,
    city: "Ouarzazate",
    region: "DRAA_TAFILALET",
    salary: "5 500 - 7 500 MAD",
    experience: "2+ ans en restauration",
    skills: ["Service en salle", "Français", "Anglais", "Connaissance des vins", "Présentation soignée"],
    deadline: "2026-05-10",
    createdAt: "2026-03-15",
    description:
      "Restaurant panoramique avec vue sur l'Atlas recherche un chef de rang expérimenté pour la saison haute. Service à l'assiette, conseil client et coordination avec la cuisine. Environnement exceptionnel aux portes du désert.",
    company: {
      id: "c8",
      name: "Kasbah Tamadot",
      logo: null,
      verified: true,
      description:
        "Hôtel-kasbah de luxe au pied de l'Atlas, propriété de Virgin Limited Edition, offrant une expérience unique entre désert et montagne.",
      city: "Ouarzazate",
      sector: "Hôtellerie de luxe",
      website: "https://www.kasbahtamadot.com",
      activeJobs: 2,
    },
  },
]
